export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GROUP_LOADED = "GROUP_LOADED";
export const GROUP_LOADING = "GROUP_LOADING";
export const GROUP_LOAD_FAIL = "GROUP_LOAD_FAIL";
export const GET_INVITES = "GET_INVITES";

export const ASSIGNMENT_LOADING = "ASSIGNMENT_LOADING";
export const ASSIGNMENT_LOADED = "ASSIGNMENT_LOADED";
export const ASSIGNMENT_FAILED = "ASSIGNMENT_FAILED";
